book/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (isset($_COOKIE['token']) || session()->get('account')!="") {
        if(session()->get('account')!=""){
            switch (session()->get('status')) {
                case 'IR':
                    return redirect('/student');
                case 'Admin':
                    return redirect('/admin');
                case 'head':
                    return redirect('/detail');
                case 'teacher':
                    return redirect('/judge');
                case 'office':
                    return redirect('/head');
                default:
                    return  redirect('Undefined');
            }
        }
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
        $json = file_get_contents($url, false, $context);
        //print($json);

        $json = json_decode($json);
        $data["Faccount"]=$json->account;
        $data["Fname"]=$json->name;
        $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();

        if ($account->count() > 0) {
            DB::table('flights')
            ->where('id', $account[0]->id)
            ->update($data);
            $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();
            session()->flush();
            session()->put('status',  $account[0]->login);
            session()->put('account',  $account[0]->Faccount);
            session()->put('name',  $account[0]->Fname);
            session()->put('department',  $account[0]->department);
            session()->put('position',  $account[0]->position);
            $datetime = date ("Y-m-d H:i:s",mktime(date('H')+8, date('i')+15, date('s'), date('m'), date('d'), date('Y')));
            session()->put('availableTime', $datetime);
            //dd(session()->get('availableTime'));
            return redirect('/SelectIdentify');
        }
        return  redirect('Undefined');

    }

    return view('welcome');
});
Route::get('/excel', function () {
    return view('exceltest');
});
Route::get('Undefined', function () {
    return view('Undefined');
});
    Route::get('/fetchdatafortimes', 'ExcelController@show')->name('timesfetch');

    Route::get('/test', function () {
        return view('IR/index');
    });



    Route::get('/TimeRequest', 'loginTimeController@show');
    Route::get('/TimeRequestReset', 'loginTimeController@resetTime');


    /*匯入系辦權限*/
    Route::post('Exceltest/importflightsDepartOffice', 'ExcelController@importflightsDepartOffice')->name('iptOfDepartment');

    /*匯入主任權限*/
    Route::post('Exceltest/importflightsDepartHead', 'ExcelController@importflightsDepartHead')->name('iptOfDepartHead');

    /*匯入學生資料*/
    Route::post('excel/importstudents', 'ExcelController@importstudents')->name('iptOfStudents');

    /*匯入老師權限*/
    Route::post('/importflightsDepartTeacher', 'ExcelController@importflightsDepartTeacher')->name('iptOfTeacheraccount');
    /*更新老師權限*/
    Route::post('excel1/updateflightsDepartTeacher', 'ExcelController@updateflightsDepartTeacher')->name('uptOfTeacheraccount');

    /*匯入配對資料*/
    Route::post('excel1/importmatches', 'ExcelController@importmatches')->name('iptOfMatches');

    /*更新主任權限*/
    Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');

    /*更新學生資料*/
    Route::post('excel1/updatestudents', 'ExcelController@updatestudents')->name('uptOfStudents');

    /*IR更新系辦權限*/
    Route::post('excel1/IRupdate1', 'IR_ExcelController@updateflightsDepartOffice_FORIR')->name('IRDOupdate');

    /*配對匯入*/
    Route::post('excel/matchimport', 'ExcelController@matchesImporter')->name('matchesImporter');

    /*匯入尺規*/
    Route::post('excel/stepsimport', 'ExcelController@stepsImporter')->name('stepsImporter');

    Route::post('excel/importTeacherJudgement', 'importAndShowGrades@importTeacherGrades')->name('importGrades');

    Route::get('excel/show', 'importAndShowGrades@show')->name('show');

    Route::get('excel/export', 'ExcelController@expotexcel')->name('export');

    Route::get('excel/exportonlysteps', 'ExcelController@exportonlysteps')->name('exportonlysteps');//會出面向(沒有成績的)

    Route::get('excel/exportn', 'ExcelController@exportnewteacherdata')->name('exportTNewdata');//匯出新老師資料

    Route::get('excel/exportne', 'ExcelController@exportnewheaddata')->name('exportHNewdata');//匯出新主任資料

    Route::get('excel/exportnew', 'ExcelController@exportnewofficedata')->name('exportONewdata');//匯出新系辦資料

    Route::get('excel/exportnewS', 'ExcelController@exportnewStudentdata')->name('exportSNewdata');//匯出新學生資料

    Route::get('excel/exportForStandardDeviation', 'importAndShowGrades@export')->name('exportForSD');//匯出標準差

    Route::get('compare', 'compareController@show')->name('compareshow');

    Route::get('getalldepartment', 'importAndShowGrades@showalldepartment')->name('showalldepartment');

Route::resource('/admin', "admin");
Route::get('logout', function () {
    if (isset($_COOKIE['token'])) {
        setcookie("token", "", time() - 1, "/", "nuu.edu.tw");
        $url = "https://sso.nuu.edu.tw/api/logout.php";
        $data_array = array("account" => session()->get('account'));
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
    }
    session()->flush();
    return view('welcome');
});
Route::get('judge2',function(){
    return view("Teacher.index2");
});

Route::resource('/flight', "GiveOfficeLoginController"); // IR
Route::resource('/head', "GiveheadLoginController"); // 系辦
Route::resource('/student', "StudentController");   // 系辦
Route::resource('/teacher', "TeacherController"); // 系辦
Route::resource('/match', "MatchController");   // 系辦
Route::resource('/departments', "DepartmentController");  //不用做
Route::resource('/standard', "JudgeStandardController"); // 系辦
Route::resource('/detail', "GradeDetailController");
Route::resource('/judge', "JudgeController");  //老師
Route::resource('/ForIR', "ForIR");  //admin
Route::resource('/delete', "OfficeDeleteController");  //admin  軟刪除
Route::resource('/Adjust', "AdjustmentScoreController");  //IR
Route::get('/test', 'testController@show');//匯出新主任資料
Route::post('/test/gradedestroy', 'testController@gradedestroy')->name('dedepartemntgrade');//刪除系所成績
Route::post('/test/upstandard', 'testController@jsupdate')->name('jsupdate');//測試
Route::post('/test/reupdate', 'testController@reupdate')->name('reupdate');//測試
Route::get('migrateexecute','admin@update')->name('migrate');
Route::get('/teacherave', 'testController@showteacherstandard');//老師標準差

// Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');


Route::get('/Allgrade',function(){ //excel
    if(session()->get('status')=="IR"){
        return view("IR.allDepartmentScore");
    }
    return redirect('/logout');
});
Route::get('/ForWith',function(){
    Cache::put('datastatus', 'Error Message Here123' , 3);
    return redirect('match');
});
Route::get('/IRcompares',function(){
    if(session()->get('status')=="IR"){
        return view("IR.compares");
    }
    return redirect('/logout');
});

// Route::resource('/headupdatedrade', "OfficeDeleteControlle@show");
// Route::resource('/list', "OfficeDeleteControlle@show");
// Route::resource('/difference', "OfficeDeleteControlle@show");
Route::resource('/SelectIdentify', "SelectIdentifyController");  //選身分
Route::resource('/deleteteacher','DeleteTeacherController');

Route::get('/adminTable',function(){
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return redirect('/detail');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return redirect('/head');
        default:
            return redirect('Undefined');
    }
});

Route::get('/Score_range', function () {
    return view('Department/Score_range');
});

Route::get('/test2', function () {
    return view('Department.All_scores');
});
Route::get('/Differential_checklist', function () {
    return view('Differential checklist');
});

Route::get('/DepartmemtCompare', function () {
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return view('Department/compares');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return view('Department/compares');
        default:
            return redirect('Undefined');
    }
});

Route::resource('/importjudgedata', "importAndShowGrades");

Route::get('/reset', function () {
    if (isset($_COOKIE['token'])) {
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");

book/app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    //
    protected $table = "teachers";
    protected $fillable = [
         'Tname','department','Taccount','login'
    ];
}

book/app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Grade;
use App\Match;
use App\Teacher;
use App\Flight;
use \Cache;
use function MongoDB\BSON\toJSON;
use Illuminate\Support\Facades\Hash;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        if (session()->get('status')=="office" ) {
            //cookie="bwerqer123123"
            return response(view('Department.teacher'))->cookie('key', bcrypt(session()->get('account')), 60, null, null, false, false);
        } else {
            setcookie("token", "", time() - 1, "/", "nuu.edu.tw");
            $url = "https://sso.nuu.edu.tw/api/logout.php";
            $data_array = array("account" => session()->get('account'));
            $options = array(
                'http' => array(
                    'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                    'method'  => 'POST',
                    'content' => http_build_query($data_array)
                )
            );
            $context  = stream_context_create($options);
            session()->flush();
            session()->put('error', '權限不足 請重新登入');
            return view('welcome');
        }

        // return view('test');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //必丟Account date 可丟 name
        $department = session()->get('department');
        $back = $_SERVER["HTTP_REFERER"];
        $flight['Faccount'] = $request->account;
        $flight['login'] = 'teacher';
        $flight['department'] = $department;
        if ($request->name != null) $flight['Fname'] = $request->name;
        if( Flight::where('department',$department)->where('login','teacher')->where('Faccount',$flight['Faccount'])->doesntExist() ){
            Flight::insert($flight);
        }
        $teacher['Taccount'] = $request->account;
        $teacher['login'] = '2';
        $teacher['department'] = $department;
        if ($request->name != null) $teacher['Tname'] = $request->name;
        if(Teacher::where('Taccount',$request->account)->where('department',$department)->whereIn('login', [ 2, 3])->exists()){
            Cache::put('datastatus', '老師帳號已存在' , 3);
        }else{
            Teacher::insert($teacher);
            Cache::put('datastatus', '儲存成功' , 3);
        }
        return redirect()->route('teacher.index');
       
        //一個不行全部不行

        // return redirect()->route('teacher.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //
        if(session()->get('status')=='office'){
            $department = session()->get('department');
            $users = DB::table('teachers')->where('department', $department)->whereIn('login', [ 2, 3])->get();
            return json_encode($users);
        }

        return json_encode([]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // 傳進teacher表裡的id 在從teacher取出Taccount Taccount找Faccount Faccount找flights的id
        $Taccount = Teacher::where('id', $request->id)->value('Taccount');
        $department=session()->get('department');
        if ($request->name != null) {
            // 只會改teacher表的
            // if(Flight::where('Faccount', $request->account)->exists() &&  !isset($request->account) ){
            //     Flight::where('Faccount',$Taccount)->where('department',$department)->update(['Fname' => $request->name]);
            // }
            Teacher::where('id',$request->id)->update(['Tname' => $request->name]);
        }
        if ($request->account != null) {
            if(Flight::where('Faccount', $request->account)->where('department',$department)->where('login','teacher')->doesntExist()){
                $flight['Faccount'] = $request->account;
                $flight['department'] = $department;
                $flight['login'] = 'teacher'; 
                if($request->name != null)$flight['Fname'] = $request->name; 
                Flight::insert($flight);
            }else{
                Flight::where('Faccount',$Taccount)->where('department',$department)->where('login','teacher')
                    ->update(['Faccount' => $request->account]);
            }
            Teacher::where('id',$request->id)->update(['Taccount' => $request->account]);
            Match::where('Taccount',$Taccount)->where('department', $department)->whereIn('login', [ 2, 3])->update(['Taccount' => $request->account]);
            Grade::where('Taccount',$Taccount)->where('department', $department)->whereIn('login', [ 2, 3])->update(['Taccount' => $request->account]);
        }
        
        Cache::put('datastatus', '更新成功' , 3);
        return redirect()->route('teacher.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        $department=session()->get('department');
        $Taccount=Teacher::where('id', $request->id)->value('Taccount');
        $back = $_SERVER["HTTP_REFERER"];
        Teacher::where('id', $request->id)->delete();
        if(Match::where('department', $department)->whereIn('login', [ 2, 3])->where('Taccount',$Taccount)->exists()){
            Match::where('department', $department)->whereIn('login', [ 2, 3])->delete();
            Grade::where('department', $department)->whereIn('login', [ 2, 3])->delete();
            Cache::put('datastatus', '成功刪除評分老師，請重新分配老師及評分' , 3);
        }else{
            Cache::put('datastatus', '成功刪除評分老師' , 3);
        }
        return redirect()->route('teacher.index');
        
        
        // return redirect()->route('teacher.index');
    }
    
}

book/resources/views/Teacher/index2.blade.php
@extends('admin.allHeaders')
@section('content')
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
  integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
<style>
  .selected {
    background: #FFAA33;
    font-weight: bold;
  }

  .bg-infos {
    background: lightblue;
    color: black;
  }

  .buttons i {
    position: fixed;
    font-size: 50px;
    padding: 0;
    margin: 0;
    cursor: pointer;
    background-color: rgba(233, 159, 159, 0);
  }

  .up {
    position: fixed;
    bottom: calc(50% + 45px);
    right: 45px;
  }

  .down {
    position: fixed;
    bottom: calc(50%);
    right: 45px;
  }
</style>
<div id="score" @click="click">
  <div v-if="!loading">
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">設定 顯示資料</h5>
          </div>
          <div class="modal-body">
            <input type="checkbox" v-model="showStudentdata[0]">應試號碼</br>
            <input type="checkbox" v-model="showStudentdata[1]">名額類別</br>
            <input type="checkbox" v-model="showStudentdata[2]">姓名</br>
            <input type="checkbox" v-model="showStudentdata[3]">性別</br>
            <input type="checkbox" v-model="showStudentdata[4]">考生身分</br>
            <input type="checkbox" v-model="showStudentdata[5]">收入戶</br>
            <input type="checkbox" v-model="showStudentdata[6]">通訊地址區域</br>
            <input type="checkbox" v-model="showStudentdata[7]">畢業年度</br>
            <input type="checkbox" v-model="showStudentdata[8]">畢業學校</br>
            <input type="checkbox" v-model="showStudentdata[9]">學校編號</br>
            <input type="checkbox" v-model="showStudentdata[10]">書審資料</br>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    <div class="buttons">
      <i class="fas fa-angle-up up" @click="Scrolldown(-1)"></i>
      <i class="fas fa-angle-down down" @click="Scrolldown(1)"></i>
    </div>
    <div class="d-flex justify-content-end align-items-center" style="font-size:28px;">
      <i class="fas fa-angle-left" @click="Scrolllleft(-1)"></i><span
        class="font-weight-bold mx-2">@{{nowjudge+1}}</span>/
      <span class="mx-2">@{{all_item.length}}</span><i class="fas fa-angle-right" @click="Scrolllleft(1)"></i>
    </div>
    <table class="table text-center">
      <thead>
        <tr>
          <th :colspan="countshowStudentData" v-if="countshowStudentData">基本資料 <button class="btn " data-toggle="modal"
              data-target="#exampleModal"><i class="fas fa-user-cog"></i></button></th>
          <template v-for="(item, all_item_index) in all_item" v-if="all_item_index==nowjudge">
            <th v-for="(detail, header_index) in item.header" colspan="2" v-html="detail.content"
              @click="clickGetScore(detail.score[0],detail.score[1],all_item_index)"
              style="word-break: break-all; width: 300px !important;" class="text-center"
              :class="{thboder:header_index==(item.header.length-1)}"></th>
          </template>
          <th colspan="2" class="bg-infos">
            總分
          </th>
        </tr>
        <tr>
          <th class="name" v-if="showStudentdata[0]">應試號碼</th>
          <th class="name" v-if="showStudentdata[1]">名額類別</th>
          <th class="name" v-if="showStudentdata[2]">姓名</th>
          <th class="name" v-if="showStudentdata[3]">性別</th>
          <th class="name" v-if="showStudentdata[4]">考生身分</th>
          <th class="name" v-if="showStudentdata[5]">收入戶</th>
          <th class="name" v-if="showStudentdata[6]">通訊地址區域</th>
          <th class="name" v-if="showStudentdata[7]">畢業年度</th>
          <th class="name" v-if="showStudentdata[8]">畢業學校</th>
          <th class="name" v-if="showStudentdata[9]">學校編號</th>
          <th class="name" v-if="showStudentdata[10]">書審資料</th>
          <template v-for="(item, all_item_index) in all_item" v-if="all_item_index==nowjudge">
            <template v-for="(detail, header_index) in item.header">
              <th v-for="(score, index) in detail.score" class="text-center scores  scorewidth"
                :class="{thboder:(header_index==(item.header.length-1) && index==1)}">
                @{{ score }}
              </th>
            </template>
          </template>
          <th class="name bg-infos">加總</th>
          <th class="name bg-infos">加權後</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for=" (item,student_index) in student" @click="selectStudent(student_index)"
          :class="{selected:student_index==selectStudents}" style="height: 50px;" v-if="studentShow[student_index]">

          <td class="name" v-if="showStudentdata[0]">@{{item.Snum}}</td>
          <td class="name" v-if="showStudentdata[1]">@{{item.category}}</td>
          <td class="name" v-if="showStudentdata[2]">@{{item.name}}</td>
          <td class="name" v-if="showStudentdata[3]">@{{item.gender}}</td>
          <td class="name" v-if="showStudentdata[4]">@{{item.identifity}}</td>
          <td class="name" v-if="showStudentdata[5]">@{{item.income}}</td>
          <td class="name" v-if="showStudentdata[6]">@{{item.address.substr(0,6)}}</td>
          <td class="name" v-if="showStudentdata[7]">@{{item.year}}</td>
          <td class="name" v-if="showStudentdata[8]">@{{item.graduation}}</td>
          <td class="name" v-if="showStudentdata[9]">@{{item.schoolnum}}</td>
          <td class="name" v-if="showStudentdata[10]"><a
              :href="`http://irmaterials.nuu.edu.tw/storage/student_data/${department}/${item.Snum}/${item.Snum}.pdf`"
              target="_blank">查看</a>
          </td>
          <template v-for="(item1, all_item_index1) in all_item" v-if="all_item_index1==nowjudge">
            <td :colspan="item_length[all_item_index1]" class="text-center">
              <el-input-number v-model="item.score[all_item_index1]" :min="item.min[all_item_index1]"
                :max="item.max[all_item_index1]" label=""></el-input-number>
            </td>
          </template>
          <td class="name  bg-infos">@{{ sumScore(student_index) }}</td>
          <td class="name  bg-infos">@{{ sumScore2(student_index) }}</td>
        </tr>
      </tbody>
    </table>
    <div class="container my-2" v-if="!await">
      <div class="row">
        <div class="col-12">
          <form action="{{ route('judge.update', 0) }}" method="POST" v-if="student">
            <input type="hidden" name="_method" value="PUT" />
            @csrf
            <div style="display:none">
              <template v-for="item in student">
                <template v-for="items in item.score.length">
                  <input type="number" name="id[]" v-model="item.id[items-1]" />
                  <input type="number" name="score[]" v-model="item.score[items-1]" />
                  <input type="number" name="max[]" v-model="item.max[items-1]" />
                  <input type="number" name="min[]" v-model="item.min[items-1]" />
                  <br />
                </template>
              </template>
            </div>
            <button class="btn btn-block btn-primary py-2">送出</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div v-else class="container" style="height:80vh">
    <div class="row">
      <div class="col-12 pt-5">
        <div class="bouncing-loader ">
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
  <div v-if="await" class="container" style="height:80vh">
    <div class="row">
      <div class="col-12 d-flex flex-row ">
        <H1 class="text-center">請等待 系辦建置資料</H1>
      </div>
    </div>
  </div>
</div>
@endsection
@section('script')
@parent

<script>
  new Vue({
      el: "#score",
      data() {
        return {
          all_item: [],
          student: [],
          item_length: [],
          loading: false,
          selectStudents: 0,
          department: "",
          await: false,
          showStudentdata:[],
          nowjudge:0,
          studentShow:[],
        };
      },
      computed: {
        countshowStudentData(){
            var count=0
            this.showStudentdata.forEach(el => {
              if(el==true)count++
            });
              return count
        },
        allitem() {
          return this.all_item.length;
        },
        sumScore() {
          return function(index) {
            var temp = 0;
            this.student[index].score.forEach(element => {
              temp += element;
            });
            return temp;
          };
        },
        
        sumScore2() {
          return function(studentindex) {
            var temp = 0;
            for (let index = 0; index < this.student[studentindex].score.length; index++) {
              temp+=((this.all_item[index].percent*0.01)*this.student[studentindex].score[index])
            }
            return temp.toFixed(2);
          };
        }, 
      },
      methods: {
        async click(){
            const res=await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
        },          
        Scrolldown(val){
          if(val>0){
            if(this.studentShow[this.studentShow.length-1]!=true){
              this.studentShow.splice(0, 0, false);
              this.studentShow.pop()
            }
          }else{
            if(this.studentShow[0]!=true){
              this.studentShow.splice(this.studentShow.length, 0, false);
              this.studentShow.shift()
            }
          }
        },
        Scrolllleft(val){
          if(val>0){
            this.all_item.length==this.nowjudge+val ? this.$message({message: "到底了",type: "warning" ,duration:1000}): this.nowjudge+=val
          }else{
            -1==this.nowjudge+val ? this.$message({message: "最前面了!",type: "warning" ,duration:1000}): this.nowjudge+=val
          }
        },
        changePage(tab) {
          this.now = tab.index;
        },
        clickGetScore(max, min, i) {
          var score = max + min;
          this.$set(this.student[this.selectStudents].max, i, max);
          this.$set(this.student[this.selectStudents].min, i, min);
          this.$set(
            this.student[this.selectStudents].score,
            i,
            parseInt(score / 2)
          );
        },
        selectStudent(student_index) {
          this.selectStudents = student_index;
        },
        async sorts() {
          var All_total;
          for (let i = 0; i < this.student.length; i++) {
            const element = this.student[i];
            All_total = 0;
            element.score.forEach(el => {
              All_total += el;
            });
            this.student[i].All_total = All_total;
          }
          // this.student = this.student.sort(function(a, b) {
          //   return a.All_total > b.All_total ? 1 : -1;
          // });
          this.student = await this.student.sort(function(a, b) {
            return a.All_total < b.All_total ? 1 : -1;
          });
          this.$message({
            message: "排序完成",
            type: "success"
          });
        }
      },
      async created() {
        for (let i = 0; i < 11; i++) {
            this.showStudentdata.push(true)
          }
        this.loading = true;
        
        try {
          const res = await axios.get("http://irmaterials.nuu.edu.tw/judge/show");
          //const res = await axios.get("http://127.0.0.1:8000/judge/show");
          this.student = await res.data.student;
          this.department=await res.data.department;
          this.all_item = await res.data.all_item;
          this.await=!(res.data.issetstandard && res.data.issetmatch)
          
          if(this.await==true)reutrn;
          this.all_item.forEach(element => {
          this.item_length.push(element.header.length * 2);
          });
          this.student.forEach(el=>{
            this.studentShow.push(false)
          })
          for (let i = 0; i < 5; i++) { this.studentShow[i]=true }
          //console.log(this.all_item);
          
          this.loading = false;
        } catch (error) {
          alert("Server Error");
          this.loading = false;
          this.await=true;
        }      
      }
  })      
</script>
@endsection