book/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (isset($_COOKIE['token']) || session()->get('account')!="") {
        if(session()->get('account')!=""){
            switch (session()->get('status')) {
                case 'IR':
                    return redirect('/student');
                case 'Admin':
                    return redirect('/admin');
                case 'head':
                    return redirect('/detail');
                case 'teacher':
                    return redirect('/judge');
                case 'office':
                    return redirect('/head');
                default:
                    return  redirect('Undefined');
            }
        }
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
        $json = file_get_contents($url, false, $context);
        //print($json);

        $json = json_decode($json);
        $data["Faccount"]=$json->account;
        $data["Fname"]=$json->name;
        $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();

        if ($account->count() > 0) {
            DB::table('flights')
            ->where('id', $account[0]->id)
            ->update($data);
            $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();
            session()->flush();
            session()->put('status',  $account[0]->login);
            session()->put('account',  $account[0]->Faccount);
            session()->put('name',  $account[0]->Fname);
            session()->put('department',  $account[0]->department);
            session()->put('position',  $account[0]->position);
            $datetime = date ("Y-m-d H:i:s",mktime(date('H')+8, date('i')+15, date('s'), date('m'), date('d'), date('Y')));
            session()->put('availableTime', $datetime);
            //dd(session()->get('availableTime'));
            return redirect('/SelectIdentify');
        }
        return  redirect('Undefined');

    }

    return view('welcome');
});
Route::get('/excel', function () {
    return view('exceltest');
});
Route::get('Undefined', function () {
    return view('Undefined');
});
    Route::get('/fetchdatafortimes', 'ExcelController@show')->name('timesfetch');

    Route::get('/test', function () {
        return view('IR/index');
    });



    Route::get('/TimeRequest', 'loginTimeController@show');
    Route::get('/TimeRequestReset', 'loginTimeController@resetTime');


    /*匯入系辦權限*/
    Route::post('Exceltest/importflightsDepartOffice', 'ExcelController@importflightsDepartOffice')->name('iptOfDepartment');

    /*匯入主任權限*/
    Route::post('Exceltest/importflightsDepartHead', 'ExcelController@importflightsDepartHead')->name('iptOfDepartHead');

    /*匯入學生資料*/
    Route::post('excel/importstudents', 'ExcelController@importstudents')->name('iptOfStudents');

    /*匯入老師權限*/
    Route::post('/importflightsDepartTeacher', 'ExcelController@importflightsDepartTeacher')->name('iptOfTeacheraccount');
    /*更新老師權限*/
    Route::post('excel1/updateflightsDepartTeacher', 'ExcelController@updateflightsDepartTeacher')->name('uptOfTeacheraccount');

    /*匯入配對資料*/
    Route::post('excel1/importmatches', 'ExcelController@importmatches')->name('iptOfMatches');

    /*更新主任權限*/
    Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');

    /*更新學生資料*/
    Route::post('excel1/updatestudents', 'ExcelController@updatestudents')->name('uptOfStudents');

    /*IR更新系辦權限*/
    Route::post('excel1/IRupdate1', 'IR_ExcelController@updateflightsDepartOffice_FORIR')->name('IRDOupdate');

    /*配對匯入*/
    Route::post('excel/matchimport', 'ExcelController@matchesImporter')->name('matchesImporter');

    /*匯入尺規*/
    Route::post('excel/stepsimport', 'ExcelController@stepsImporter')->name('stepsImporter');

    Route::post('excel/importTeacherJudgement', 'importAndShowGrades@importTeacherGrades')->name('importGrades');

    Route::get('excel/show', 'importAndShowGrades@show')->name('show');

    Route::get('excel/export', 'ExcelController@expotexcel')->name('export');

    Route::get('excel/exportonlysteps', 'ExcelController@exportonlysteps')->name('exportonlysteps');//會出面向(沒有成績的)

    Route::get('excel/exportn', 'ExcelController@exportnewteacherdata')->name('exportTNewdata');//匯出新老師資料

    Route::get('excel/exportne', 'ExcelController@exportnewheaddata')->name('exportHNewdata');//匯出新主任資料

    Route::get('excel/exportnew', 'ExcelController@exportnewofficedata')->name('exportONewdata');//匯出新系辦資料

    Route::get('excel/exportnewS', 'ExcelController@exportnewStudentdata')->name('exportSNewdata');//匯出新學生資料

    Route::get('excel/exportForStandardDeviation', 'importAndShowGrades@export')->name('exportForSD');//匯出標準差

    Route::get('compare', 'compareController@show')->name('compareshow');

    Route::get('getalldepartment', 'importAndShowGrades@showalldepartment')->name('showalldepartment');

Route::resource('/admin', "admin");
Route::get('logout', function () {
    if (isset($_COOKIE['token'])) {
        setcookie("token", "", time() - 1, "/", "nuu.edu.tw");
        $url = "https://sso.nuu.edu.tw/api/logout.php";
        $data_array = array("account" => session()->get('account'));
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
    }
    session()->flush();
    return view('welcome');
});
Route::get('judge2',function(){
    return view("Teacher.index2");
});

Route::resource('/flight', "GiveOfficeLoginController"); // IR
Route::resource('/head', "GiveheadLoginController"); // 系辦
Route::resource('/student', "StudentController");   // 系辦
Route::resource('/teacher', "TeacherController"); // 系辦
Route::resource('/match', "MatchController");   // 系辦
Route::resource('/departments', "DepartmentController");  //不用做
Route::resource('/standard', "JudgeStandardController"); // 系辦
Route::resource('/detail', "GradeDetailController");
Route::resource('/judge', "JudgeController");  //老師
Route::resource('/ForIR', "ForIR");  //admin
Route::resource('/delete', "OfficeDeleteController");  //admin  軟刪除
Route::resource('/Adjust', "AdjustmentScoreController");  //IR
Route::get('/test', 'testController@show');//匯出新主任資料
Route::post('/test/gradedestroy', 'testController@gradedestroy')->name('dedepartemntgrade');//刪除系所成績
Route::post('/test/upstandard', 'testController@jsupdate')->name('jsupdate');//測試
Route::post('/test/reupdate', 'testController@reupdate')->name('reupdate');//測試
Route::get('migrateexecute','admin@update')->name('migrate');
Route::get('/teacherave', 'testController@showteacherstandard');//老師標準差

// Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');


Route::get('/Allgrade',function(){ //excel
    if(session()->get('status')=="IR"){
        return view("IR.allDepartmentScore");
    }
    return redirect('/logout');
});
Route::get('/ForWith',function(){
    Cache::put('datastatus', 'Error Message Here123' , 3);
    return redirect('match');
});
Route::get('/IRcompares',function(){
    if(session()->get('status')=="IR"){
        return view("IR.compares");
    }
    return redirect('/logout');
});

// Route::resource('/headupdatedrade', "OfficeDeleteControlle@show");
// Route::resource('/list', "OfficeDeleteControlle@show");
// Route::resource('/difference', "OfficeDeleteControlle@show");
Route::resource('/SelectIdentify', "SelectIdentifyController");  //選身分
Route::resource('/deleteteacher','DeleteTeacherController');

Route::get('/adminTable',function(){
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return redirect('/detail');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return redirect('/head');
        default:
            return redirect('Undefined');
    }
});

Route::get('/Score_range', function () {
    return view('Department/Score_range');
});

Route::get('/test2', function () {
    return view('Department.All_scores');
});
Route::get('/Differential_checklist', function () {
    return view('Differential checklist');
});

Route::get('/DepartmemtCompare', function () {
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return view('Department/compares');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return view('Department/compares');
        default:
            return redirect('Undefined');
    }
});

Route::resource('/importjudgedata', "importAndShowGrades");

Route::get('/reset', function () {
    if (isset($_COOKIE['token'])) {
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");

book/resources/views/Differential checklist.blade.php
@extends('admin.allHeaders')
@section('content')


<div id="app" class="pt-5 ">
    <div class="container">
        <div class="row my-2">
            <a href="/storage/Excel%20example/差分檢和.xlsx"><button type="button" name="" id=""
                    class="btn btn-success">下載Excel</button></a>
        </div>
        <div class="row">
            <table class="table">
                <tbody>
                    <tr>
                        <td>級距別</td>
                        <td>分數區間</td>
                        <td>區間機率%</td>
                        <td>人數比例</td>
                        <td>人數比例取2位小數</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>75以下</td>
                        <td>1.6</td>
                        <td>0.016</td>
                        <td>0.02</td>
                    </tr>
                    <tr>
                        <td>2</td>
                        <td>76-77</td>
                        <td>3.4</td>
                        <td>0.034</td>
                        <td>0.03</td>
                    </tr>
                    <tr>
                        <td>3</td>
                        <td>78-79</td>
                        <td>7.4</td>
                        <td>0.074</td>
                        <td>0.07</td>
                    </tr>
                    <tr>
                        <td>4</td>
                        <td>80-81</td>
                        <td>12.8</td>
                        <td>0.128</td>
                        <td>0.13</td>
                    </tr>
                    <tr>
                        <td>5</td>
                        <td>82-83</td>
                        <td>17.6</td>
                        <td>0.176</td>
                        <td>0.18</td>
                    </tr>
                    <tr>
                        <td>6</td>
                        <td>84-85</td>
                        <td>19.2</td>
                        <td>0.192</td>
                        <td>0.19</td>
                    </tr>
                    <tr>
                        <td>7</td>
                        <td>86-87</td>
                        <td>16.6</td>
                        <td>0.166</td>
                        <td>0.17</td>
                    </tr>
                    <tr>
                        <td>8</td>
                        <td>88-89</td>
                        <td>11.4</td>
                        <td>0.114</td>
                        <td>0.11</td>
                    </tr>
                    <tr>
                        <td>9</td>
                        <td>90-91</td>
                        <td>6.2</td>
                        <td>0.062</td>
                        <td>0.06</td>
                    </tr>
                    <tr>
                        <td>10</td>
                        <td>92-93</td>
                        <td>2.6</td>
                        <td>0.026</td>
                        <td>0.03</td>
                    </tr>
                    <tr>
                        <td>11</td>
                        <td>94以上</td>
                        <td>1.2</td>
                        <td>0.012</td>
                        <td>0.01</td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                        <td>100.0</td>
                        <td>1.000</td>
                        <td>1.00</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="row" style="height: 300px;">
            <ve-histogram :data="chartData" width="100%"></ve-histogram>
        </div>
    </div>

</div>
@endsection
@section('script')
@parent
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/v-charts/lib/index.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/v-charts/lib/style.min.css">
<script>
    new Vue({
        el:"#app",
        data () {
            return {
                chartData: {
                columns: ['級距別', '人數比例'],
                rows: [
                    { '級距別':1, '人數比例':0.02},
                    { '級距別':2, '人數比例':0.03},
                    { '級距別':3, '人數比例':0.07},
                    { '級距別':4, '人數比例':0.13},
                    { '級距別':5, '人數比例':0.18},
                    { '級距別':6, '人數比例':0.19},
                    { '級距別':7, '人數比例':0.17},
                    { '級距別':8, '人數比例':0.11},
                    { '級距別':9, '人數比例':0.06},
                    { '級距別':10, '人數比例':0.03},
                    { '級距別':11, '人數比例':0.01},
                ]
                }
            }
        }
    })
</script>
@endsection

book/resources/views/Selectidentify.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
  <title>選擇身分</title>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet" />
  <style>
    * {
      font-family: "Noto Sans TC", sans-serif;
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark" id="headers" >
    <a class="navbar-brand" href="/judge">選擇身分</a>

    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
      aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
      <div class="dropdown ml-auto">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          {{ Session::get('name')}}
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <a class="dropdown-item" href="/logout">登出</a>
        </div>
      </div>
    </div>
  </nav>
  <div id="app" class=" mt-3">
    <div class="container">
      <div class="row">
        <div class="col-12 text-center">
          <h1>選擇身分</h1>
        </div>
        <div class="col-12 ">
          <div class="row">
            <div class="col-4 mt-4 d-flex justify-content-center" v-for="item in data">
              <div class="card p-2" style="width: 18rem;">
                <img src="/storage/588023633.png" class="card-img-top" alt="..." />
                <div class="card-body">
                  <div>帳號:@{{item.Faccount}}</div>
                  <div>姓名:@{{item.Fname}}</div>
                  <div>系組:@{{item.department}}</div>
                  <div>身份:@{{item.login}}</div>
                </div>
                <form action="{{ route('SelectIdentify.update', 0) }}" method="post"
                  class="d-flex flew-row justify-content-center">
                  @csrf
                  <input type="hidden" name="_method" value="PUT" />
                  <input type="hidden" name="id" v-model="item.id" />
                  <button type="submit" class="btn btn-primary">選擇</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/element-ui/2.13.0/index.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.0/axios.js"></script>
  <script>
    new Vue({
        el: "#app",
        data() {
          return {
            data: [
              
            ]
          };
        },
        methods: {
        async click(){
          const res=await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
        },},
        created() {
          axios
            .get("http://irmaterials.nuu.edu.tw/SelectIdentify/show")
            .then(res => {
              ////console.log(res.data);
              this.data = res.data;
            });
        }
      });
  </script>
</body>

</html>

book/resources/views/test.blade.php
<!-- <form action="{{route('iptOfStudents')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}}
    <input type="file" name="select_file">
    <input type="submit" value="宋拉">
</form> -->
match.update
<form action="{{ route('match.update', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf
    <input  name="Taccount[]" value="T1234" />
    <input  name="Snum[]" value="S1234,S1235" />
    <input  name="Taccount[]" value="T1235" />
    <input  name="Snum[]" value="S1235,S1236" />
    <input  name="Taccount[]" value="T1236" />
    <input  name="Snum[]" value="S1234,S1236" />


    <button type="submit" name=""  class="btn btn-danger">
        update
    </button>
</form>

match.destroy
<form action="{{ route('match.destroy', 0) }}" method="post">
    <input type="hidden" name="_method" value="DELETE" />
    @csrf
    <input  name="number" value="6" />
    <button type="submit" name=""  class="btn btn-danger">
    delete
    </button>
</form>


<form action="{{ route('head.store') }}" method="post">

    @csrf
    <input type="hidden" name="id" value="3" />
    <input type="hidden" name="Faccount" value="1" />
    <!-- <input type="hidden" name="Mitem" value="0" /> -->
    <input type="hidden" name="date" value="2019-9-27" />
    <!-- <input type="hidden" name="name" value="234" />
    <input type="hidden" name="account" value="435io" />
    <input type="hidden" name="date" value="2019-8-27" />  -->
    <button type="submit" name=""  class="btn btn-danger">
        store
    </button>
</form>
standard.destroy
<form action="{{ route('standard.destroy', 0) }}" method="post">
    <input type="hidden" name="_method" value="DELETE" />
    @csrf
    <input type name="project" value="109學測" />

    <input type name="Bitem[]" value="0" />
    <input type name="Mitem[]" value="0" />
    <input type name="Sitem[]" value="0" />
    <input type name="title[]" value="面相一" />
    <input type name="HighScore[]" value="" />
    <input type name="lowScore[]" value="" />
    <input type name="percent[]" value="" />

    <input type name="Bitem[]" value="0" />
    <input type name="Mitem[]" value="0" />
    <input type name="Sitem[]" value="1" />
    <input type name="title[]" value="面相一-0-1" />
    <input type name="HighScore[]" value="10" />
    <input type name="lowScore[]" value="6" />
    <input type name="login[]" value="2" />

    <input type name="Bitem[]" value="0" />
    <input type name="Mitem[]" value="0" />
    <input type name="Sitem[]" value="2" />
    <input type name="title[]" value="面相一-0-2" />
    <input type name="HighScore[]" value="5" />
    <input type name="lowScore[]" value="0" />
    <input type name="login[]" value="2" />

    <input type name="Bitem[]" value="0" />
    <input type name="Mitem[]" value="1" />
    <input type name="Sitem[]" value="0" />
    <input type name="title[]" value="" />
    <input type name="HighScore[]" value="" />
    <input type name="lowScore[]" value="" />
    <input type name="login[]" value="2" />

    <input type name="Bitem[]" value="0" />
    <input type name="Mitem[]" value="1" />
    <input type name="Sitem[]" value="1" />
    <input type name="title[]" value="面相一-1-1" />
    <input type name="HighScore[]" value="5" />
    <input type name="lowScore[]" value="0" />
    <input type name="login[]" value="2" />

    <input type name="Bitem[]" value="1" />
    <input type name="Mitem[]" value="0" />
    <input type name="Sitem[]" value="0" />
    <input type name="title[]" value="面相二" />
    <input type name="HighScore[]" value="" />
    <input type name="lowScore[]" value="" />
    <input type name="login[]" value="2" />

    <input type name="Bitem[]" value="1" />
    <input type name="Mitem[]" value="0" />
    <input type name="Sitem[]" value="1" />
    <input type name="title[]" value="面相二-0-1" />
    <input type name="HighScore[]" value="10" />
    <input type name="lowScore[]" value="6" />
    <input type name="login[]" value="2" />

    <input type name="Bitem[]" value="1" />
    <input type name="Mitem[]" value="0" />
    <input type name="Sitem[]" value="2" />
    <input type name="title[]" value="面相二-0-1" />
    <input type name="HighScore[]" value="5" />
    <input type name="lowScore[]" value="0" />
    <input type name="login[]" value="2" />

    <button type="submit" name=""  class="btn btn-danger">
        delete
    </button>

    
</form>


<!-- <form action="{{ route('student.destroy', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf
    <input type="hidden" name="id" value="1" />

    <button type="submit" name=""  class="btn btn-danger">
        delete
    </button>
</form> -->
judge.update
<form action="{{ route('judge.update', 0) }}" method="POST">
  <input type="hidden" name="_method" value="PUT" />
    @csrf
    <input type name="id[]" value="25" />
    <input type name="score[]" value="5" />
    <input type name="max[]" value="5" />
    <input type name="min[]" value="0" />

    <!-- <input type name="id[]" value="44" />
    <input type name="score[]" value="6" />

    <input type name="id[]" value="45" />
    <input type name="score[]" value="6" /> -->


    <button type="submit" name=""  class="btn btn-danger">
    update
    </button>

</form>

student.update
<form action="{{ route('student.update', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf
    
    <input  name="id" value="2" />
    <input  name="olddepartment" value="資訊管理學系" />
    <input  name="department" value="經營管理學系" />

    <button type="submit" name=""  class="btn btn-danger">
        update
    </button>
</form>

teacher.update
<form action="{{ route('teacher.update', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf
    <input  name="name" value="test" />
    <input  name="id" value="5" />
    <input  name="account" value="T1237" />
    <!-- <input  name="Snum[]" value="S043546,S023123" /> -->


    <button type="submit" name=""  class="btn btn-danger">
        update
    </button>
</form>
teacher.delete
<form action="{{ route('teacher.destroy', 0) }}" method="post">
    <input type="hidden" name="_method" value="DELETE" />
    @csrf
    <input type name="id" value="5" />
    
    <button type="submit" name=""  class="btn btn-danger">
        delete
    </button>

   
</form>

student.update
<form action="{{ route('student.update', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf
    <input  name="Sname" value="test" />
    <input  name="id" value="1" />
    <input  name="Snum" value="S1237" />
    <!-- <input  name="Snum[]" value="S043546,S023123" /> -->


    <button type="submit" name=""  class="btn btn-danger">
        update
    </button>
</form>
student.delete
<form action="{{ route('student.destroy', 0) }}" method="post">
    <input type="hidden" name="_method" value="DELETE" />
    @csrf
    <input type name="id" value="5" />
    
    <button type="submit" name=""  class="btn btn-danger">
        delete
    </button>

   
</form>

office 軟刪除
<form action="{{ route('delete.update', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf


    <button type="submit" name=""  class="btn btn-danger">
        delete
    </button>
</form>

teacher 軟刪除
<form action="{{ route('deleteteacher.update', 0) }}" method="POST">
    <input type="hidden" name="_method" value="PUT" />
    @csrf

    <input type name="type" value="2" />
    <button type="submit" name=""  class="btn btn-danger">
        delete
    </button>
</form>


departmentgrade.destroy
<!-- <form action="{{ route('dedepartemntgrade') }}" method="POST">
    <input type="hidden" name="_method" value="DELETE" />
    @csrf
    <input  name="department" value="" />
    <button type="submit" name=""  class="btn btn-danger">
    delete
    </button>
</form> -->
<form action="{{route('dedepartemntgrade')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}}
    <input  name="department" value="">
    <input type="submit" value="delete">
</form>
<!-- <form action="{{route('iptOfDepartHead')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}}
    <input type="file" name="select_file">
    <input type="submit" value="主任匯入測試">
</form> -->
js up test
<form action="{{route('jsupdate')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}}
    <input  name="project" value="">
    <input  name="newproject" value="">
    <input type="submit" value="delete">
</form>

js up test
<form action="{{route('reupdate')}}" method="post" enctype="multipart/form-data">
    {{csrf_field()}}
    
    <input type="submit" value="reupdate">
</form>