book/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (isset($_COOKIE['token']) || session()->get('account')!="") {
        if(session()->get('account')!=""){
            switch (session()->get('status')) {
                case 'IR':
                    return redirect('/student');
                case 'Admin':
                    return redirect('/admin');
                case 'head':
                    return redirect('/detail');
                case 'teacher':
                    return redirect('/judge');
                case 'office':
                    return redirect('/head');
                default:
                    return  redirect('Undefined');
            }
        }
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
        $json = file_get_contents($url, false, $context);
        //print($json);

        $json = json_decode($json);
        $data["Faccount"]=$json->account;
        $data["Fname"]=$json->name;
        $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();

        if ($account->count() > 0) {
            DB::table('flights')
            ->where('id', $account[0]->id)
            ->update($data);
            $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();
            session()->flush();
            session()->put('status',  $account[0]->login);
            session()->put('account',  $account[0]->Faccount);
            session()->put('name',  $account[0]->Fname);
            session()->put('department',  $account[0]->department);
            session()->put('position',  $account[0]->position);
            $datetime = date ("Y-m-d H:i:s",mktime(date('H')+8, date('i')+15, date('s'), date('m'), date('d'), date('Y')));
            session()->put('availableTime', $datetime);
            //dd(session()->get('availableTime'));
            return redirect('/SelectIdentify');
        }
        return  redirect('Undefined');

    }

    return view('welcome');
});
Route::get('/excel', function () {
    return view('exceltest');
});
Route::get('Undefined', function () {
    return view('Undefined');
});
    Route::get('/fetchdatafortimes', 'ExcelController@show')->name('timesfetch');

    Route::get('/test', function () {
        return view('IR/index');
    });



    Route::get('/TimeRequest', 'loginTimeController@show');
    Route::get('/TimeRequestReset', 'loginTimeController@resetTime');


    /*匯入系辦權限*/
    Route::post('Exceltest/importflightsDepartOffice', 'ExcelController@importflightsDepartOffice')->name('iptOfDepartment');

    /*匯入主任權限*/
    Route::post('Exceltest/importflightsDepartHead', 'ExcelController@importflightsDepartHead')->name('iptOfDepartHead');

    /*匯入學生資料*/
    Route::post('excel/importstudents', 'ExcelController@importstudents')->name('iptOfStudents');

    /*匯入老師權限*/
    Route::post('/importflightsDepartTeacher', 'ExcelController@importflightsDepartTeacher')->name('iptOfTeacheraccount');
    /*更新老師權限*/
    Route::post('excel1/updateflightsDepartTeacher', 'ExcelController@updateflightsDepartTeacher')->name('uptOfTeacheraccount');

    /*匯入配對資料*/
    Route::post('excel1/importmatches', 'ExcelController@importmatches')->name('iptOfMatches');

    /*更新主任權限*/
    Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');

    /*更新學生資料*/
    Route::post('excel1/updatestudents', 'ExcelController@updatestudents')->name('uptOfStudents');

    /*IR更新系辦權限*/
    Route::post('excel1/IRupdate1', 'IR_ExcelController@updateflightsDepartOffice_FORIR')->name('IRDOupdate');

    /*配對匯入*/
    Route::post('excel/matchimport', 'ExcelController@matchesImporter')->name('matchesImporter');

    /*匯入尺規*/
    Route::post('excel/stepsimport', 'ExcelController@stepsImporter')->name('stepsImporter');

    Route::post('excel/importTeacherJudgement', 'importAndShowGrades@importTeacherGrades')->name('importGrades');

    Route::get('excel/show', 'importAndShowGrades@show')->name('show');

    Route::get('excel/export', 'ExcelController@expotexcel')->name('export');

    Route::get('excel/exportonlysteps', 'ExcelController@exportonlysteps')->name('exportonlysteps');//會出面向(沒有成績的)

    Route::get('excel/exportn', 'ExcelController@exportnewteacherdata')->name('exportTNewdata');//匯出新老師資料

    Route::get('excel/exportne', 'ExcelController@exportnewheaddata')->name('exportHNewdata');//匯出新主任資料

    Route::get('excel/exportnew', 'ExcelController@exportnewofficedata')->name('exportONewdata');//匯出新系辦資料

    Route::get('excel/exportnewS', 'ExcelController@exportnewStudentdata')->name('exportSNewdata');//匯出新學生資料

    Route::get('excel/exportForStandardDeviation', 'importAndShowGrades@export')->name('exportForSD');//匯出標準差

    Route::get('compare', 'compareController@show')->name('compareshow');

    Route::get('getalldepartment', 'importAndShowGrades@showalldepartment')->name('showalldepartment');

Route::resource('/admin', "admin");
Route::get('logout', function () {
    if (isset($_COOKIE['token'])) {
        setcookie("token", "", time() - 1, "/", "nuu.edu.tw");
        $url = "https://sso.nuu.edu.tw/api/logout.php";
        $data_array = array("account" => session()->get('account'));
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
    }
    session()->flush();
    return view('welcome');
});
Route::get('judge2',function(){
    return view("Teacher.index2");
});

Route::resource('/flight', "GiveOfficeLoginController"); // IR
Route::resource('/head', "GiveheadLoginController"); // 系辦
Route::resource('/student', "StudentController");   // 系辦
Route::resource('/teacher', "TeacherController"); // 系辦
Route::resource('/match', "MatchController");   // 系辦
Route::resource('/departments', "DepartmentController");  //不用做
Route::resource('/standard', "JudgeStandardController"); // 系辦
Route::resource('/detail', "GradeDetailController");
Route::resource('/judge', "JudgeController");  //老師
Route::resource('/ForIR', "ForIR");  //admin
Route::resource('/delete', "OfficeDeleteController");  //admin  軟刪除
Route::resource('/Adjust', "AdjustmentScoreController");  //IR
Route::get('/test', 'testController@show');//匯出新主任資料
Route::post('/test/gradedestroy', 'testController@gradedestroy')->name('dedepartemntgrade');//刪除系所成績
Route::post('/test/upstandard', 'testController@jsupdate')->name('jsupdate');//測試
Route::post('/test/reupdate', 'testController@reupdate')->name('reupdate');//測試
Route::get('migrateexecute','admin@update')->name('migrate');
Route::get('/teacherave', 'testController@showteacherstandard');//老師標準差

// Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');


Route::get('/Allgrade',function(){ //excel
    if(session()->get('status')=="IR"){
        return view("IR.allDepartmentScore");
    }
    return redirect('/logout');
});
Route::get('/ForWith',function(){
    Cache::put('datastatus', 'Error Message Here123' , 3);
    return redirect('match');
});
Route::get('/IRcompares',function(){
    if(session()->get('status')=="IR"){
        return view("IR.compares");
    }
    return redirect('/logout');
});

// Route::resource('/headupdatedrade', "OfficeDeleteControlle@show");
// Route::resource('/list', "OfficeDeleteControlle@show");
// Route::resource('/difference', "OfficeDeleteControlle@show");
Route::resource('/SelectIdentify', "SelectIdentifyController");  //選身分
Route::resource('/deleteteacher','DeleteTeacherController');

Route::get('/adminTable',function(){
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return redirect('/detail');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return redirect('/head');
        default:
            return redirect('Undefined');
    }
});

Route::get('/Score_range', function () {
    return view('Department/Score_range');
});

Route::get('/test2', function () {
    return view('Department.All_scores');
});
Route::get('/Differential_checklist', function () {
    return view('Differential checklist');
});

Route::get('/DepartmemtCompare', function () {
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return view('Department/compares');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return view('Department/compares');
        default:
            return redirect('Undefined');
    }
});

Route::resource('/importjudgedata', "importAndShowGrades");

Route::get('/reset', function () {
    if (isset($_COOKIE['token'])) {
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");

book/resources/views/admin/allHeaders.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>系務辦公室</title>
    <!-- Required meta tags -->
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="https://www.nuu.edu.tw/var/file/0/1000/msys_1000_9991812_60080.jpg" type="image/x-icon" />


    <link rel="stylesheet" href="https://unpkg.com/element-ui/lib/theme-chalk/index.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+TC&display=swap" rel="stylesheet" />
    <style>
        * {
            font-family: "Noto Sans TC", sans-serif;
        }

        @keyframes bouncing-loader {
            to {
                opacity: 0.1;
                transform: translate3d(0, -1rem, 0);
            }
        }

        .bouncing-loader {
            display: flex;
            justify-content: center;
        }

        .bouncing-loader>div {
            width: 1rem;
            height: 1rem;
            margin: 3rem 0.2rem;
            background: #8385aa;
            border-radius: 50%;
            animation: bouncing-loader 0.6s infinite alternate;
        }

        .bouncing-loader>div:nth-child(2) {
            animation-delay: 0.2s;
        }

        .bouncing-loader>div:nth-child(3) {
            animation-delay: 0.4s;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark" id="headers">
        @if(session()->get('status')=="head")
        <a class="navbar-brand" href="{{route('judge.index')}}">主任查看與評分</a>
        @elseif(session()->get('status')=="office")
        <a class="navbar-brand" href="{{route('head.index')}}">系務辦公室</a>
        @elseif(session()->get('status')=="Admin")
        <a class="navbar-brand" href="/admin">Admin</a>
        @elseif(session()->get('status')=="IR")
        <a class="navbar-brand" href="/flight">管理者 建立系辦人員</a>
        @else
        <a class="navbar-brand" href="/judge">書審老師評分</a>
        @endif

        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"
                aria-hidden="true"></i> </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                @if(session()->get('status')=="head")
                <li class="nav-item" :class="{ 'active': location[5]}">
                    <a class="nav-link" href="/detail">榜單試算</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[7]}">
                    <a class="nav-link" href="/Differential_checklist">差分檢和試算表</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[8]}">
                    <a class="nav-link" href="/DepartmemtCompare">差分檢核</a>
                </li>
                @elseif(session()->get('status')=="office")
                <li class="nav-item" :class="{ 'active': location[0]}">
                    <a class="nav-link" href="/head">建立主任資料</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[1]}">
                    <a class="nav-link" href="/student">查看學生資料</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[2]}">
                    <a class="nav-link" href="/teacher">評審委員資料</a>
                </li>

                <li class="nav-item" :class="{ 'active': location[3]}">
                    <a class="nav-link" href="/match">分配評分人員</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[4]}">
                    <a class="nav-link" href="/standard">評分項目與分數區間</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[5]}">
                    <a class="nav-link" href="/detail">查看評分細節</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[7]}">
                    <a class="nav-link" href="/Differential_checklist">差分檢和試算表</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[8]}">
                    <a class="nav-link" href="/DepartmemtCompare">差分檢核</a>
                </li>
                @elseif(session()->get('status')=="Admin")
                <li class="nav-item" :class="{ 'active': location[0]}">
                    <a class="nav-link" href="/admin">切換身分</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[1]}">
                    <a class="nav-link" href="/ForIR">給予IR權限</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[2]}">
                    <a class="nav-link" href="/adminTable">顯示table</a>
                </li>
                @elseif(session()->get('status')=="IR")
                <li class="nav-item" :class="{ 'active': location[1]}">
                    <a class="nav-link" href="/student">學生資料</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[0]}">
                    <a class="nav-link" href="/flight">給予系辦權限</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[2]}">
                    <a class="nav-link" href="/Allgrade">所有系所評分資料</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[3]}">
                    <a class="nav-link" href="/importjudgedata">匯入計算標準差</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[4]}">
                    <a class="nav-link" href="/IRcompares">查看差分</a>
                </li>
                @else
                <li class="nav-item" :class="{ 'active': location[0]}">
                    <a class="nav-link" href="/judge">書審評分</a>
                </li>
                <li class="nav-item" :class="{ 'active': location[7]}">
                    <a class="nav-link" href="/Differential_checklist">差分檢和試算表</a>
                </li>
                @endif

            </ul>
            <div class="dropdown ml-auto d-flex flex-row">
                <div class="text-white w-100 my-auto">
                    剩餘時間 @{{time }}
                </div>
                <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ Session::get('name')}}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="/logout">登出</a>
                </div>
            </div>
        </div>
    </nav>

    <!-- Button trigger modal -->

    <!-- Modal -->

    <section class="mt-3" id="app">
        @yield('content')
    </section>

    @section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.6.10/vue.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.19.0/axios.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/element-ui/2.13.0/index.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/element-ui/2.13.0/locale/zh-TW.min.js'></script>
    <script>
        ELEMENT.locale(ELEMENT.lang.zhTW);
    </script>
    <script>
        new Vue({
            el: "#headers",
            data() {
                return {
                    location: [false, false, false, false, false, false, false, false],
                    time:"",
                    Ortime:"",
                    msg:"{{ cache('datastatus') }}"
                };
            },
            methods: {
                async getTime(){
                    const res=await axios.get("http://irmaterials.nuu.edu.tw/TimeRequest")
                    this.Ortime=res.data
                    this.time=this.parseData(res.data)
                },

                async checktime(){
                    if(this.Ortime==60*5 || this.Ortime==60*3 || this.Ortime==60*1){
                        this.$message({
                            message: "請注意時間，盡快保存後登出，時間到自動套跳轉登出請注意!",
                            type: "warning"
                        });
                    }
                    if(this.Ortime<=0){
                        window.location.href = "http://irmaterials.nuu.edu.tw/logout";
                    }                    
                },
                timer() {
                    this.time = setInterval(async () => {
                        await this.getTime()
                        await this.checktime()
                    }, 1000)
                },
                parseData(duration){
                    var seconds = Math.floor(duration % 60),
                    minutes = Math.floor((duration / ( 60)) % 60),
                    hours = Math.floor((duration / ( 60 * 60)) % 24);
                    hours = (hours < 10) ? "0" + hours : hours;
                    minutes=(minutes < 10) ? "0" + minutes : minutes; 
                    seconds=(seconds < 10) ? "0" + seconds : seconds;
                    return hours + ":" + minutes + ":" + seconds ;
                },
                setTime() {
                    this.getTime()
                    this.timer()
                },
                stopTime() {
                    if (this.time) {
                        clearInterval(this.time)
                    }
                }
            },
            async created() {
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
                await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")

                var web = location.href.split("/");
                switch (web[web.length - 1]) {
                    case 'flight':
                    case 'head':
                    case 'judge':
                    case 'admin':
                        this.location[0] = true
                        break;
                    case 'ForIR':
                    case 'student':
                        this.location[1] = true
                        break;
                    case 'adminTable':
                    case 'student':
                    case 'teacher':
                    case 'Allgrade':
                    case 'allDepartmentScore':
                        this.location[2] = true
                        break;
                    case 'match':
                    case 'importjudgedata':
                        this.location[3] = true
                        break;
                    case 'standard':
                    case 'IRcompares':
                        this.location[4] = true
                        break;
                    case 'detail':
                        this.location[5] = true
                        break;
                    case 'Differential_checklist':
                        this.location[7] = true
                        break;
                    case 'DepartmemtCompare':
                        this.location[8] = true
                        break;
                    default:
                        this.location[6] = true
                        break;
                }
                await this.setTime()
                if(this.msg!=""){
                    this.$message({message: this.msg,duration:3000})
                }
            }               
        })
    </script>
    @show
</body>

</html>

book/resources/views/admin/forIR.blade.php
@extends('admin.allHeaders')
@section('content')

<!-- Modal -->
<div class="modal fade" id="TypingInput" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true" >
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">新增管理者資料</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('ForIR.store')}}" method="post">
                    @csrf
                    <div class="container">
                        <div class="row">
                            <div class="form-group">
                                <label for="">帳號</label>
                                <input type="text" name="Faccount" class="form-control" placeholder=""
                                    aria-describedby="helpId" v-model="type.account" required />
                                <small id="helpId" class="text-muted">輸入學校帳號</small>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" @click="CloseInput">
                            關閉
                        </button>
                        <button type="submit" class="btn btn-primary">儲存</button>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
<!-- Modal -->
<div class="modal fade" id="changeinput" tabindex="-1" role="dialog" aria-labelledby="modelTitleId" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">修改管理者資料</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('ForIR.update',0)}}" method="post">
                    <input type="hidden" name="_method" value="PUT">
                    <input type="hidden" name="id" v-model="change.id">
                    @csrf
                    <div class="container">
                        <div class="row">
                            <div class="form-group">
                                <label for="">帳號</label>
                                <input type="text" name="Faccount" class="form-control" placeholder=""
                                    aria-describedby="helpId" v-model="change.account" required />
                                <small id="helpId" class="text-muted">輸入學校帳號</small>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal" @click="CloseInput">
                            關閉
                        </button>
                        <button type="submit" class="btn btn-primary">儲存</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="container" v-if="loading" @click="click">
    <div class="row">
        <div class="col-12">
            <button type="button" name="" class="btn btn-success mx-2" data-target="#TypingInput" data-toggle="modal">
                新增管理者資料
            </button>

        </div>
        <table class="table mt-2">
            <thead>
                <tr>
                    <th>帳號</th>
                    <th>姓名</th>
                    <th>修改</th>
                    <th>刪除</th>
                </tr>
            </thead>
            <tbody>
                <tr v-for="(item,index) in all">
                    <td>@{{ item.Faccount }}</td>
                    <td>@{{ item.Fname }}</td>
                    <td>
                        <button type="button" name="" class="btn btn-info" @click="changedata(index)">
                            修改
                        </button>
                    </td>
                    <td>
                        <form action="{{route('ForIR.destroy',0)}}" method="post">
                            <input type="hidden" name="_method" value="DELETE">
                            @csrf
                            <input type="hidden" name="id" v-model="item.id">
                            <button onclick="return confirm('確認刪除此筆資料?');" type="submit" name="" class="btn btn-danger">
                                刪除
                            </button>
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div v-else class="container" style="height:80vh">
    <div class="row">
        <div class="col-12 pt-5">
            <div class="bouncing-loader ">
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
@parent
<script>
    new Vue({
        el: "#app",
        data() {
            return {
                loading: false,
                type: {
                    Fname: "",
                    Faccount: "",
                    department: "",
                    date: ""
                },
                change: {
                    id: 0,
                    Fname: "",
                    Faccount: "",
                    department: "",
                    date: ""
                },
                all: [],
                addname: "",
                upname: "",
                key:""
            };
        },
        methods: {
            async click(){
            const res=await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
        },
            changedata(index) {
                this.change.id = this.all[index].id;
                this.change.name = this.all[index].Fname;
                this.change.account = this.all[index].Faccount;
                this.change.department = this.all[index].department;
                this.change.date = this.all[index].date;
                $("#changeinput").modal("show");
            },
            CloseInput() {
                //console.log("close");
                this.type.name = "";
                this.type.account = "";
                this.type.department = "";
                this.type.date = "";
                $("#TypingInput").modal("hide");
            }
        },
        computed: {
            getupdate() {
                var f = 123;


                return f.length != 0 ? true : false;
            }
        },
        created() {
            axios.get("http://irmaterials.nuu.edu.tw/ForIR/show").then(res => { //book.test
                this.all = res.data;
                this.loading = true;
            });
        }
    });
</script>
@endsection