book/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if (isset($_COOKIE['token']) || session()->get('account')!="") {
        if(session()->get('account')!=""){
            switch (session()->get('status')) {
                case 'IR':
                    return redirect('/student');
                case 'Admin':
                    return redirect('/admin');
                case 'head':
                    return redirect('/detail');
                case 'teacher':
                    return redirect('/judge');
                case 'office':
                    return redirect('/head');
                default:
                    return  redirect('Undefined');
            }
        }
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
        $json = file_get_contents($url, false, $context);
        //print($json);

        $json = json_decode($json);
        $data["Faccount"]=$json->account;
        $data["Fname"]=$json->name;
        $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();

        if ($account->count() > 0) {
            DB::table('flights')
            ->where('id', $account[0]->id)
            ->update($data);
            $account = DB::table('flights')->where('Faccount', '=', $json->account)->get();
            session()->flush();
            session()->put('status',  $account[0]->login);
            session()->put('account',  $account[0]->Faccount);
            session()->put('name',  $account[0]->Fname);
            session()->put('department',  $account[0]->department);
            session()->put('position',  $account[0]->position);
            $datetime = date ("Y-m-d H:i:s",mktime(date('H')+8, date('i')+15, date('s'), date('m'), date('d'), date('Y')));
            session()->put('availableTime', $datetime);
            //dd(session()->get('availableTime'));
            return redirect('/SelectIdentify');
        }
        return  redirect('Undefined');

    }

    return view('welcome');
});
Route::get('/excel', function () {
    return view('exceltest');
});
Route::get('Undefined', function () {
    return view('Undefined');
});
    Route::get('/fetchdatafortimes', 'ExcelController@show')->name('timesfetch');

    Route::get('/test', function () {
        return view('IR/index');
    });



    Route::get('/TimeRequest', 'loginTimeController@show');
    Route::get('/TimeRequestReset', 'loginTimeController@resetTime');


    /*匯入系辦權限*/
    Route::post('Exceltest/importflightsDepartOffice', 'ExcelController@importflightsDepartOffice')->name('iptOfDepartment');

    /*匯入主任權限*/
    Route::post('Exceltest/importflightsDepartHead', 'ExcelController@importflightsDepartHead')->name('iptOfDepartHead');

    /*匯入學生資料*/
    Route::post('excel/importstudents', 'ExcelController@importstudents')->name('iptOfStudents');

    /*匯入老師權限*/
    Route::post('/importflightsDepartTeacher', 'ExcelController@importflightsDepartTeacher')->name('iptOfTeacheraccount');
    /*更新老師權限*/
    Route::post('excel1/updateflightsDepartTeacher', 'ExcelController@updateflightsDepartTeacher')->name('uptOfTeacheraccount');

    /*匯入配對資料*/
    Route::post('excel1/importmatches', 'ExcelController@importmatches')->name('iptOfMatches');

    /*更新主任權限*/
    Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');

    /*更新學生資料*/
    Route::post('excel1/updatestudents', 'ExcelController@updatestudents')->name('uptOfStudents');

    /*IR更新系辦權限*/
    Route::post('excel1/IRupdate1', 'IR_ExcelController@updateflightsDepartOffice_FORIR')->name('IRDOupdate');

    /*配對匯入*/
    Route::post('excel/matchimport', 'ExcelController@matchesImporter')->name('matchesImporter');

    /*匯入尺規*/
    Route::post('excel/stepsimport', 'ExcelController@stepsImporter')->name('stepsImporter');

    Route::post('excel/importTeacherJudgement', 'importAndShowGrades@importTeacherGrades')->name('importGrades');

    Route::get('excel/show', 'importAndShowGrades@show')->name('show');

    Route::get('excel/export', 'ExcelController@expotexcel')->name('export');

    Route::get('excel/exportonlysteps', 'ExcelController@exportonlysteps')->name('exportonlysteps');//會出面向(沒有成績的)

    Route::get('excel/exportn', 'ExcelController@exportnewteacherdata')->name('exportTNewdata');//匯出新老師資料

    Route::get('excel/exportne', 'ExcelController@exportnewheaddata')->name('exportHNewdata');//匯出新主任資料

    Route::get('excel/exportnew', 'ExcelController@exportnewofficedata')->name('exportONewdata');//匯出新系辦資料

    Route::get('excel/exportnewS', 'ExcelController@exportnewStudentdata')->name('exportSNewdata');//匯出新學生資料

    Route::get('excel/exportForStandardDeviation', 'importAndShowGrades@export')->name('exportForSD');//匯出標準差

    Route::get('compare', 'compareController@show')->name('compareshow');

    Route::get('getalldepartment', 'importAndShowGrades@showalldepartment')->name('showalldepartment');

Route::resource('/admin', "admin");
Route::get('logout', function () {
    if (isset($_COOKIE['token'])) {
        setcookie("token", "", time() - 1, "/", "nuu.edu.tw");
        $url = "https://sso.nuu.edu.tw/api/logout.php";
        $data_array = array("account" => session()->get('account'));
        $options = array(
            'http' => array(
                'header'  => "Content-type: application/x-www-form-urlencoded\r\n",
                'method'  => 'POST',
                'content' => http_build_query($data_array)
            )
        );
        $context  = stream_context_create($options);
    }
    session()->flush();
    return view('welcome');
});
Route::get('judge2',function(){
    return view("Teacher.index2");
});

Route::resource('/flight', "GiveOfficeLoginController"); // IR
Route::resource('/head', "GiveheadLoginController"); // 系辦
Route::resource('/student', "StudentController");   // 系辦
Route::resource('/teacher', "TeacherController"); // 系辦
Route::resource('/match', "MatchController");   // 系辦
Route::resource('/departments', "DepartmentController");  //不用做
Route::resource('/standard', "JudgeStandardController"); // 系辦
Route::resource('/detail', "GradeDetailController");
Route::resource('/judge', "JudgeController");  //老師
Route::resource('/ForIR', "ForIR");  //admin
Route::resource('/delete', "OfficeDeleteController");  //admin  軟刪除
Route::resource('/Adjust', "AdjustmentScoreController");  //IR
Route::get('/test', 'testController@show');//匯出新主任資料
Route::post('/test/gradedestroy', 'testController@gradedestroy')->name('dedepartemntgrade');//刪除系所成績
Route::post('/test/upstandard', 'testController@jsupdate')->name('jsupdate');//測試
Route::post('/test/reupdate', 'testController@reupdate')->name('reupdate');//測試
Route::get('migrateexecute','admin@update')->name('migrate');
Route::get('/teacherave', 'testController@showteacherstandard');//老師標準差

// Route::post('excel1/updateflightsDepartHead', 'ExcelController@updateflightsDepartHead')->name('uptOfDepartHead');


Route::get('/Allgrade',function(){ //excel
    if(session()->get('status')=="IR"){
        return view("IR.allDepartmentScore");
    }
    return redirect('/logout');
});
Route::get('/ForWith',function(){
    Cache::put('datastatus', 'Error Message Here123' , 3);
    return redirect('match');
});
Route::get('/IRcompares',function(){
    if(session()->get('status')=="IR"){
        return view("IR.compares");
    }
    return redirect('/logout');
});

// Route::resource('/headupdatedrade', "OfficeDeleteControlle@show");
// Route::resource('/list', "OfficeDeleteControlle@show");
// Route::resource('/difference', "OfficeDeleteControlle@show");
Route::resource('/SelectIdentify', "SelectIdentifyController");  //選身分
Route::resource('/deleteteacher','DeleteTeacherController');

Route::get('/adminTable',function(){
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return redirect('/detail');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return redirect('/head');
        default:
            return redirect('Undefined');
    }
});

Route::get('/Score_range', function () {
    return view('Department/Score_range');
});

Route::get('/test2', function () {
    return view('Department.All_scores');
});
Route::get('/Differential_checklist', function () {
    return view('Differential checklist');
});

Route::get('/DepartmemtCompare', function () {
    switch (session()->get('status')) {
        case 'IR':
            return redirect('/student');
        case 'Admin':
            return view('admin/DB');
        case 'head':
            return view('Department/compares');
        case 'teacher':
            return redirect('/judge');
        case 'office':
            return view('Department/compares');
        default:
            return redirect('Undefined');
    }
});

Route::resource('/importjudgedata', "importAndShowGrades");

Route::get('/reset', function () {
    if (isset($_COOKIE['token'])) {
        $url = "https://sso.nuu.edu.tw/api/checkToken.php";
        $data_array = array("token" => $_COOKIE['token'], "system_name" => "書審輔助系統");

book/app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    //

    protected $table="departments";
    protected $fillable = ['name','department','departmentid'];
}

book/app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Department;
use Illuminate\Http\Request;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //
        $departments = DB::table('student_departments')->select('department', 'departmentid')->distinct()->get();
        return json_encode($departments);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

book/resources/views/Department/All_scores.blade.php
@extends('admin.allHeaders')
@include('Department.calculation')

book/resources/views/Department/calculation.blade.php
@section('content')
<style>
    .display {
        display: none;
    }

    table tbody {
        display: block;
        height: 60vh;
        overflow-y: scroll;
    }

    table thead,
    tbody tr {
        display: table;
        width: 100%;
        table-layout: fixed;
    }

    table thead {
        width: calc(100% - 1em);
    }

    .scores:nth-child(odd)::after {
        content: '~';
        display: inline-block;
        height: 100%;
        width: 50%;
        vertical-align: top;
        text-align: end;
        translate(50%, 50%);
    }
</style>
<div id="score" @click="click">
    <div class="d-flex flex-row justify-content-end">
        <a href="/deleteteacher/show?type=1">
            <button class="btn btn-warning m-2">
                關閉老師評分
            </button>
        </a>
        <a href="/deleteteacher/show?type=2">
            <button class="btn btn-success m-2">
                回復老師評分
            </button>
        </a>
        <a href="/excel/export">
            <button class="btn btn-primary m-2">
                下載Excel
            </button>
        </a>
    </div>
    <el-tabs type="border-card" @tab-click="changePage" v-if="!loading">
        <el-tab-pane :label="item.title" v-for="(item, index) in all_item" :key="index" :stretch="true">
            <table class="table">
                <thead class="sticky-top position-static">
                    <tr>
                        <th colspan="2">評分項目 與 學生</th>
                        <template v-for="(item, all_item_index) in all_item">
                            <th class="text-center" v-for="(detail, header_index) in item.header" colspan="2"
                                v-html="detail.content" :class="{ display: all_item_index!= now}"
                                style="word-break: break-all;"></th>
                        </template>
                    </tr>
                    <tr>
                        <th colspan="1">准考證號碼</th>
                        <th colspan="1">姓名</th>
                        <template v-for="(item, all_item_index) in all_item">
                            <template v-for="(detail, header_index) in item.header">
                                <th v-for="(score, index) in detail.score" class="text-center "
                                    :class="{ display: all_item_index!= now}">
                                    @{{ score }}
                                </th>
                            </template>
                        </template>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item, student_index) in student">
                        <td scope="row" colspan="1">@{{ item.Snum }}</td>
                        <td scope="row" colspan="1">@{{ item.name }}</td>
                        <template v-for="(item1, all_item_index1) in all_item">
                            <template v-for="(item3,index)  in item.scroe[all_item_index1]">
                                <template v-for="(item4,index4) in item3">
                                    <template v-for="(item5,index5) in item4">
                                        <td :colspan="colspan(all_item_index1,item4)" class="text-center"
                                            :class="{ display : all_item_index1 != now}">@{{ teachername(index5) }} 老師 :
                                            @{{item5}}</td>

                                    </template>
                                </template>
                            </template>
                        </template>
                    </tr>
                </tbody>
            </table>
        </el-tab-pane>
    </el-tabs>
    <div v-else class="container" style="height:80vh">
        <div class="row">
            <div class="col-12 pt-5">
                <div class="bouncing-loader ">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection
@section('script')
@parent

<!-- import JavaScript -->


<script>
    new Vue({
        el: "#score",
        data() {
            return {
                now: 0,
                all_item: [],
                student: [],
                item_length: [],
                loading: false,
                teacher:[]
            };
        },
        computed: {
            teachername(){
                return function (index) {
                    var name;
                    this.teacher.forEach(element => {
                        if (element.id==index) {
                            //console.log(element.id, element.Tname);
                            name=element.Tname
                        }
                    });
                    return name;

                }
            },
            allitem() {
                return this.all_item.length;
            },
            sumScore() {
                return function(index) {
                    var temp = 0;
                    this.student[index].score.forEach(element => {
                        temp += element;
                    });
                    return temp;
                };
            },
            colspan(){
                return function(index,items) {
                    var count=0
                    for (var prop in items) {
                        count++;
                    }                 
                    return this.item_length[index]/count
                };
            }
        },
        methods: {
        async click(){
            const res=await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
        },
            changePage(tab) {
                this.now = tab.index;
            },

        },
        async created() {
            this.loading = true;
            const res = await axios.get("http://irmaterials.nuu.edu.tw/detail/All_scores");
            this.student = res.data.student;
            this.all_item = res.data.all_item ?res.data.all_item :[];
            this.teacher=res.data.teacher;
            if(this.all_item.length==0)this.$message({message: "請先建置系所相關資料",duration:3000})
            this.all_item.forEach(element => {
                this.item_length.push(element.header.length * 2);
            });
            //console.log(res.data);
            
            this.loading = false;
        }
    });
</script>
@endsection

book/resources/views/Department/director.blade.php
@extends('admin.allHeaders')
@section('content')
<section class="pt-5" id="app" @click="click">
    <div class="modal fade" id="InputForExcel" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">匯入</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row my-2">
                            <form action="{{route('iptOfDepartHead')}}" method="post" enctype="multipart/form-data"
                                class="d-flex">
                                @csrf
                                <input type="file" id="ExcelAdd" name="select_file" style="display: none"
                                    accept=".xlsx, .xls, .csv" v-on:change="onFileChange($event)" />
                                <button type="button" class="btn btn-success" onclick="$('#ExcelAdd').click()">

                                    新增
                                </button>
                                <span class="mx-2 my-auto">新增資料在原本資料後方，不會將原資料刪除<br><small>@{{addname}}</small></span>

                                <button type="submit" class="btn btn-success" v-if="addname!=''">送出</button>



                            </form>
                        </div>
                        <div class="row my-2">
                            <form action="{{route('uptOfDepartHead')}}" method="post" enctype="multipart/form-data"
                                class="d-flex">
                                @csrf
                                <input type="file" id="ExcelUpdate" name="select_file" style="display: none"
                                    accept=".xlsx, .xls, .csv" v-on:change="onFileChange2($event)" />
                                <button type="button" class="btn btn-primary" onclick="$('#ExcelUpdate').click()">

                                    更新
                                </button>
                                <span class="mx-2 my-auto">取代原本資料，不會保留原有資料<br><small>@{{upname}}</small></span>
                                <button type="submit" class="btn btn-primary"
                                    onclick="return confirm('請注意取代原本資料，『不會保留』原有資料!!!');" v-if="upname!=''">送出</button>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer d-flex justify-content-between">
                    <a href="/storage/Excel%20example/head.xlsx">範例檔案</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">
                        關閉
                    </button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="TypingInput" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">新增主任資料</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('head.store')}}" method="post">
                        @csrf
                        <div class="container">
                            <div class="row">
                                <div class="form-group">
                                    <label for="">帳號</label>
                                    <input type="text" name="Faccount" class="form-control" aria-describedby="helpId"
                                        v-model="type.account" required />
                                    <small id="helpId" class="text-muted">輸入學校帳號</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="">姓名</label>
                                    <input type="text" name="Fname" class="form-control" placeholder=""
                                        aria-describedby="helpId" v-model="type.name" />
                                    <small id="helpId" class="text-muted">輸入名稱 可為空值</small>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" @click="CloseInput">
                                關閉
                            </button>
                            <button type="submit" class="btn btn-primary">儲存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="changeinput" tabindex="-1" role="dialog" aria-labelledby="modelTitleId"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">修改主任資料</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('head.update',0)}}" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="id" v-model="change.id">
                        @csrf
                        <div class="container">
                            <div class="row">
                                <div class="form-group">
                                    <label for="">帳號</label>
                                    <input type="text" name="Faccount" class="form-control" placeholder=""
                                        aria-describedby="helpId" v-model="change.Faccount" required />
                                    <small id="helpId" class="text-muted">輸入學校帳號</small>
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group">
                                    <label for="">姓名</label>
                                    <input type="text" name="Fname" class="form-control" placeholder=""
                                        aria-describedby="helpId" v-model="change.Fname" />
                                    <small id="helpId" class="text-muted">輸入名稱</small>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal" @click="CloseInput">
                                關閉
                            </button>
                            <button type="submit" class="btn btn-primary">儲存</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container" v-if="loading">
        <div class="row">
            <div class="col-12">
                <button type="button" name="" class="btn btn-primary mx-2" data-toggle="modal"
                    data-target="#InputForExcel">
                    匯入主任資料
                </button>
                <button type="button" name="" class="btn btn-success mx-2" data-target="#TypingInput"
                    data-toggle="modal">
                    新增主任資料
                </button>
                <button class="btn btn-primary mx-2 float-right"
                    onclick="location.href='{{route('exportHNewdata')}}'">匯出主任</button>
            </div>
            <table class="table mt-2">
                <thead>
                    <tr>
                        <th>編號</th>
                        <th>帳號</th>
                        <th>姓名</th>
                        <th>系組</th>
                        <th>修改</th>
                        <th>刪除</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for="(item,index) in all">
                        <td scope="row">@{{ index+1 }}</td>
                        <td>@{{ item.Faccount }}</td>
                        <td>@{{ item.Fname }}</td>
                        <td>@{{ item.department }}</td>
                        <td>
                            <button type="button" name="" class="btn btn-info" @click="changedata(index)">
                                修改
                            </button>
                        </td>
                        <td>
                            <form action="{{route('head.destroy',0)}}" method="post">
                                <input type="hidden" name="_method" value="DELETE">
                                @csrf
                                <input type="hidden" name="id" v-model="item.id">
                                <button type="submit" name="" onclick="return confirm('確認刪除此筆資料?');"
                                    class="btn btn-danger">
                                    刪除
                                </button>
                            </form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div v-else class="container" style="height:80vh">
        <div class="row">
            <div class="col-12 pt-5">
                <div class="bouncing-loader ">
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
            </div>
        </div>
    </div>
</section>

@endsection
@section('script')
@parent
<script>
    new Vue({
        el: "#app",
        data() {
            return {
                loading: false,
                type: {
                    name: "",
                    account: "",
                    department: ""
                },
                change: {
                    id: 0,
                    name: "",
                    account: "",
                    department: ""
                },
                all: [],
                departments: [],
                addname: "",
                upname: ""
            };
        },
        methods: {
        async click(){
            const res=await axios.get("http://irmaterials.nuu.edu.tw/TimeRequestReset")
        },
            changedata(index) {
                this.change.id = this.all[index].id;
                this.change.Fname = this.all[index].Fname;
                this.change.Faccount = this.all[index].Faccount;
                this.change.department = this.all[index].department;
                $("#changeinput").modal("show");
            },
            onFileChange(e) {
                if (e.target.files.length != 0) {
                    //console.log(e.target.files[0].name);
                    this.addname = e.target.files[0].name;
                }
            },
            onFileChange2(e) {
                if (e.target.files.length != 0) {
                    //console.log(e.target.files[0].name);
                    this.upname = e.target.files[0].name;
                }
            },
            CloseInput() {
                //console.log("close");
                this.type.Fname = "";
                this.type.Faccount = "";
                this.type.department = "";
                $("#TypingInput").modal("hide");
            }
        },
        created() {
            this.loading = false;
            axios.get("http://irmaterials.nuu.edu.tw/head/show").then(res => {
                //  axios.get("http://127.0.0.1:8000/head/show").then(res => {
                this.all = res.data;
                this.loading = true;
            });
        }
    });
</script>
@endsection

book/resources/views/Department/student.blade.php
@extends('admin.allHeaders')
@include('IR.students')